version: "3.8"
services:
  web:
    build: .
    ports:
      - 3000:3000
  api:
    image: "espilonius/knowhows-backend:latest"
    environment:
      DB_URL: mongodb://db/KnowHows
  db:
    image: mongo:4.0-xenial
    ports:
      - 27027:27017
    volumes:
      -  KnowHows:/data/db
volumes:
  KnowHows: