name: Docker build and push to docker hub

on:
  push:
    branches: 
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/knowhows-frontend:latest" .
          docker tag "${{ secrets.DOCKER_USERNAME }}/knowhows-frontend:latest" "${{ secrets.DOCKER_USERNAME }}/knowhows-backend:${{ github.sha }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/knowhows-frontend:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/knowhows-frontend:${{ github.sha }}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
